### ISSUE TITLE
s22-6pm-4 test merging of degradationRate frontend + backend CRUD operations

### ISSUE THREAD

**Issue by laszlo-tw** [ucsb-cs156-s22/s22-6pm-happycows#66]
In this issue we will verify that the degradation rate frontend and backend CRUD operation implementations (@neelmurthy1 's PR #50 and @humwooter 's PR #55 , respectively) work together.

we will focus on
- passing tests
- working build

why?
1. @neelmurthy1 's PR #50 is currently not passing some checks that have to do with the tests he implemented and we believe that this is because the tests rely on backend functionality and his PR lacks the backend implementation (because it is in @humwooter 's #55). we will see if combining the two implementations will resolve this issue and fix it if not
2. since there is a backlog of PRs waiting to be approved and merged, we kind of have to extrapolate into the future. we are doing this to try to anticipate and prevent problems that will occur when the PRs are merged and also try to ensure that the build runs as expected because if i'm understanding correctly we are not allowed to debug after tonight (6/1)

### to-do checklist:
- [x] create a new branch for testing (ex. `s22-6pm-4-kr-nm-TEST-BRANCH-degradation-rate-crud`)
- [x] pull from both @neelmurthy1 's and @humwooter 's branches: `nm-addDegRateToFormAndTableComponents` and `KR-added-field-degradation-rate-toAPI-final`, respectively
- [x] run test (`npm run test`), coverage (`npm run coverage`), and stryker (`npx stryker run`) and ensure all tests pass and there is full coverage. **debug here if necessary**. *EDITED NOTE:* during this process @sangitakunapuli managed to fix the frontend tests on @neelmurthy1 's #50 so that the PR is now ready for approval!
- [x] deploy to heroku qa and ensure that the build works as expected (can refer to acceptance criteria of issues #24 and #22 and also i will add some below) **debug here if necessary**
* edit: sk- deployed ! looks good:D

### Acceptance criteria for testing:
Testing:
- [x] Tests still pass 100% (`npm run test`)
- [x] Codecov remains full at 100% (`npm run coverage`)
- [x] Stryker remains full at 100% (`npx stryker run`)
- [ ] perhaps we can also create a DRAFT PR and let the github checks run to see if it passes all 11 checks

### Acceptance criteria for Heroku QA deployment:
Create operations:
- [x] Degradation rate number field can be seen by Admin on Create Commons page
- [x] degradationRate field value can be set by Admin during commons creation via Show Leaderboard? checkbox field on Create Commons page
- [x] degradationRate field value set by Admin during Commons creation is POSTed to the backend when Create button is clicked
- [x] degradationRate field value set by Admin during Commons creation is correctly displayed in corresponding row in the Commons table
- [x]  degradationRate field does not accept negative values, and displays an appropriate error message when an invalid value is entered

Update operations: 
- [x] Degradation Rate number field can be seen by admin on Edit Commons page
- [x] degradationRate field value can be modified by Admin during commons updating via Show Leaderboard? checkbox field on Edit Commons page
- [x] degradationRate field value modified by Admin during Commons updating is PUT into the backend when Update button is clicked
- [x] degradationRate field value modified by Admin during Commons creation is correctly displayed in corresponding row in the Commons table
- [x] degradationRate field does not accept negative values, and displays an appropriate error message when an invalid value is entered
